Globalwarmin/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Windows;
using System.Web.Mvc;
using Global.Data;
using Global.Services.IService;
using Global.Services.Service;

namespace Globalwarmin.Controllers
{
    public class QuestionController : Controller
    {
        IQuestionService _questionService;
        IUserService _userService;
        IScoreService _scoreService;
        public QuestionController()
        {
            _questionService = new QuestionService();
            _userService = new UserService();
            _scoreService = new ScoreService();
        }


        // GET: Question
        public ActionResult Index()
        {
            IList<Question> questions = _questionService.GetAllQuestions();
            return View(questions);
        }

        // GET: Question/Details/5
        public ActionResult Details(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(Question _question)
        {
            if (ModelState.IsValid)
            {
                int questionId = _questionService.GetNextID();
                _question.QuestionId = questionId;
                _questionService.CreateQuestion(_question);
                return RedirectToAction("Index");
            }
            return View(_question);
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // POST: Question/Edit/5
        [HttpPost]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                _questionService.UpdateQuestion(question);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Question/Delete/5
        public ActionResult Delete(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // POST: Question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                _questionService.DeleteQuestion(id);
                return RedirectToAction("Index");
            }
            return View();


        }
        public ActionResult AskQuestion(int id)
        {
            if (Session["CurrentScore"] == null)
            {
                Session["CurrentScore"] = 0;
            }

            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        public ActionResult AnswerQuestion(int thisquestionid, string clickedanswer)
        {
            Question thisquestion = _questionService.GetQuestionById(thisquestionid);

            if (thisquestion.RightAnswer == clickedanswer)
            {
                int currentscore = (int)Session["CurrentScore"];
                currentscore += thisquestion.Score;
                Session["CurrentScore"] = currentscore;
                return View("success", thisquestion);
            }
            else
            {
                return View("wrong", thisquestion);
            }
        }
        public ActionResult GetQuestionsForQuizId(int id)
        {
            IList<int> questionsids = _questionService.GetQuestionByQuizId(id);
            int nextquestion = questionsids[0];
            questionsids.RemoveAt(0);
            Session["questionstoask"] = questionsids;
            Session["quizid"] = id;
            return RedirectToAction("AskQuestion", new { id = nextquestion });

        }
        public ActionResult NextQuestion()
        {
            IList<int> questionsids = (IList<int>)Session["questionstoask"];
            try
            {
                int nextquestion = questionsids[0];
                questionsids.RemoveAt(0);
                Session["questionstoask"] = questionsids;
                return RedirectToAction("AskQuestion", new { id = nextquestion });
            }
            catch
            {
                int finalscore = (int)Session["CurrentScore"];
                Session.Abandon();
                string Username = User.Identity.Name;
                string userid = _userService.GetUserIdForUserName(Username);
                int quizid = (int)Session["quizid"];

                Score NewScore = new Score();
                NewScore.DateTime = DateTime.Now;
                NewScore.Score1 = finalscore;
                NewScore.quizid = quizid;
                NewScore.UserId = userid;
                _scoreService.createscore(NewScore);

                return View("Endofquiz", finalscore);
            }
        }
    }
}

Globalwarmin/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Data;
using Global.Services.IService;
using Global.Services.Service;
using Globalwarmin.ViewModels;

namespace Globalwarmin.Controllers
{
    public class QuizController : Controller
    {
        private IQuizService _QuizService;
        private IUserService _UserService;

        public QuizController()
        {
            _UserService = new UserService();
            _QuizService = new QuizService();
        }

        // GET: Quiz
        public ActionResult Index()
        {
            IList<Quiz> allquiz = _QuizService.GetQuizs();
            return View(allquiz);
        }

        // GET: Quiz/Details/5
        public ActionResult Details(int id)
        {
            Quiz quiz;
            quiz = _QuizService.GetQuizById(id);
            return View(quiz);
        }

        // GET: Quiz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quiz/Create
        [HttpPost]
        public ActionResult Create(Quiz _quiz)
        {
            if (ModelState.IsValid)
            {
                _QuizService.CreateQuiz(_quiz);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Quiz/Edit/5
        public ActionResult Edit(int id)
        {
            Quiz quiz = _QuizService.GetQuizById(id);
            return View(quiz);
        }

        // POST: Quiz/Edit/5
        [HttpPost]
        public ActionResult Edit(Quiz quiz)
        {
            if(ModelState.IsValid)
            {
                _QuizService.UpdateQuiz(quiz);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Quiz/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_QuizService.GetQuizById(id));
        }

        // POST: Quiz/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                _QuizService.DeleteQuiz(id);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult ShowHighScoresForQuizID(int id)
        {
            IList<Score> scores;
            scores = _QuizService.GetScoresForQuizID(id);

            IList<HighScoresViewModel> viewModelList = new List<HighScoresViewModel>();

            foreach(Score score in scores)
            {
                HighScoresViewModel viewModel = new HighScoresViewModel()
                {
                    Score = score.Score1,
                    UserName = _UserService.GetUserByID(score.UserId).UserName.Split('@')[0],
                    QuizName = _QuizService.GetQuizById(score.quizid).Title,
                    Date = score.DateTime
                };
                viewModelList.Add(viewModel);
            }
            return View(viewModelList);
        }
    }
}

Globalwarmin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Services.IService;
using Global.Services.Service;
using Global.Data;
using Globalwarmin.ViewModels;

namespace Globalwarmin.Controllers
{
    public class UserController : Controller
    {
        private IUserService _userservice;
        private IQuizService _quizservice;

        public UserController()
        {
            _userservice = new UserService();
            _quizservice = new QuizService();

        }
        // GET: User
        public ActionResult Index()
        {
            return View(_userservice.Getusers());
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GetAllScoresForAllUsers(string userid)
        {
            IList<Score> scores;
           scores = _userservice.GetAllScoresForAllUsers(userid);
            IList<HighScoresViewModel> viewModelList = new List<HighScoresViewModel>();

            foreach (Score score in scores)
            {
                HighScoresViewModel viewModel = new HighScoresViewModel()
                {
                    Score = score.Score1,
                    UserName = _userservice.GetUserByID(score.UserId).UserName.Split('@')[0],
                    QuizName = _quizservice.GetQuizById(score.quizid).Title,
                    Date = score.DateTime
                };
                viewModelList.Add(viewModel);
            }
            return View(viewModelList);
        }

        public ActionResult GetQuizScoresForUserId(int id)
        {
            IList<Score> scores;
            scores = _userservice.GetQuizScoresForUserId(_userservice.GetUserIdForUserName(User.Identity.Name),id);
            IList<HighScoresViewModel> viewModelList = new List<HighScoresViewModel>();

            foreach (Score score in scores)
            {
                HighScoresViewModel viewModel = new HighScoresViewModel()
                {
                    Score = score.Score1,
                    UserName = _userservice.GetUserByID(score.UserId).UserName.Split('@')[0],
                    QuizName = _quizservice.GetQuizById(score.quizid).Title,
                    Date = score.DateTime
                };
                viewModelList.Add(viewModel);
            }
            return View(viewModelList);

        }
    }
}

Globalwarmin/Views/Quiz/Create.cshtml
@model Global.Data.Quiz

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Globalwarmin/Views/Quiz/Delete.cshtml
@model Global.Data.Quiz

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quiz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Globalwarmin/Views/Quiz/Details.cshtml
@model Global.Data.Quiz

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Quiz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QuizID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Globalwarmin/Views/Quiz/Edit.cshtml
@model Global.Data.Quiz

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.QuizID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Globalwarmin/Views/Quiz/Index.cshtml
@model IEnumerable<Global.Data.Quiz>

@{
    ViewBag.Title = "Index";
}

<h2>Quizzes</h2>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a href="@Url.Action("GetQuestionsForQuizId", "Question", new { id = item.QuizID })"> Take Quiz</a>
            </td>
            <td>
                @Html.ActionLink("All High Scores", "ShowHighScoresForQuizID", new { id = item.QuizID }) |
                @Html.ActionLink("My High Scores", "GetQuizScoresForUserId", "User", new { id = item.QuizID }, null)

            </td>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.QuizID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.QuizID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.QuizID })
                </td>
            }
        </tr>
    }

</table>

Globalwarmin/Views/Quiz/ShowHighScoresForQuizID.cshtml
@model IEnumerable<Globalwarmin.ViewModels.HighScoresViewModel>

@{
    ViewBag.Title = "High Scores";
    int count = 1;
}

<h2>High Scores</h2>

<table class="table">
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuizName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @count
            @{ count++; }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuizName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
    </tr>
}

</table>