Globalwarmin/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Windows;
using System.Web.Mvc;
using Global.Data;
using Global.Services.IService;
using Global.Services.Service;

namespace Globalwarmin.Controllers
{
    public class QuestionController : Controller
    {
        IQuestionService _questionService;
        IUserService _userService;
        IScoreService _scoreService;
        public QuestionController()
        {
            _questionService = new QuestionService();
            _userService = new UserService();
            _scoreService = new ScoreService();
        }


        // GET: Question
        public ActionResult Index()
        {
            IList<Question> questions = _questionService.GetAllQuestions();
            return View(questions);
        }

        // GET: Question/Details/5
        public ActionResult Details(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(Question _question)
        {
            if (ModelState.IsValid)
            {
                int questionId = _questionService.GetNextID();
                _question.QuestionId = questionId;
                _questionService.CreateQuestion(_question);
                return RedirectToAction("Index");
            }
            return View(_question);
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // POST: Question/Edit/5
        [HttpPost]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                _questionService.UpdateQuestion(question);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Question/Delete/5
        public ActionResult Delete(int id)
        {
            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        // POST: Question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                _questionService.DeleteQuestion(id);
                return RedirectToAction("Index");
            }
            return View();


        }
        public ActionResult AskQuestion(int id)
        {
            if (Session["CurrentScore"] == null)
            {
                Session["CurrentScore"] = 0;
            }

            Question question = _questionService.GetQuestionById(id);
            return View(question);
        }

        public ActionResult AnswerQuestion(int thisquestionid, string clickedanswer)
        {
            Question thisquestion = _questionService.GetQuestionById(thisquestionid);

            if (thisquestion.RightAnswer == clickedanswer)
            {
                int currentscore = (int)Session["CurrentScore"];
                currentscore += thisquestion.Score;
                Session["CurrentScore"] = currentscore;
                return View("success", thisquestion);
            }
            else
            {
                return View("wrong", thisquestion);
            }
        }
        public ActionResult GetQuestionsForQuizId(int id)
        {
            IList<int> questionsids = _questionService.GetQuestionByQuizId(id);
            int nextquestion = questionsids[0];
            questionsids.RemoveAt(0);
            Session["questionstoask"] = questionsids;
            Session["quizid"] = id;
            return RedirectToAction("AskQuestion", new { id = nextquestion });

        }
        public ActionResult NextQuestion()
        {
            IList<int> questionsids = (IList<int>)Session["questionstoask"];
            try
            {
                int nextquestion = questionsids[0];
                questionsids.RemoveAt(0);
                Session["questionstoask"] = questionsids;
                return RedirectToAction("AskQuestion", new { id = nextquestion });
            }
            catch
            {
                int finalscore = (int)Session["CurrentScore"];
                Session.Abandon();
                string Username = User.Identity.Name;
                string userid = _userService.GetUserIdForUserName(Username);
                int quizid = (int)Session["quizid"];

                Score NewScore = new Score();
                NewScore.DateTime = DateTime.Now;
                NewScore.Score1 = finalscore;
                NewScore.quizid = quizid;
                NewScore.UserId = userid;
                _scoreService.createscore(NewScore);

                return View("Endofquiz", finalscore);
            }
        }
    }
}

Globalwarmin/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Data;
using Global.Services.IService;
using Global.Services.Service;
using Globalwarmin.ViewModels;

namespace Globalwarmin.Controllers
{
    public class QuizController : Controller
    {
        private IQuizService _QuizService;
        private IUserService _UserService;

        public QuizController()
        {
            _UserService = new UserService();
            _QuizService = new QuizService();
        }

        // GET: Quiz
        public ActionResult Index()
        {
            IList<Quiz> allquiz = _QuizService.GetQuizs();
            return View(allquiz);
        }

        // GET: Quiz/Details/5
        public ActionResult Details(int id)
        {
            Quiz quiz;
            quiz = _QuizService.GetQuizById(id);
            return View(quiz);
        }

        // GET: Quiz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quiz/Create
        [HttpPost]
        public ActionResult Create(Quiz _quiz)
        {
            if (ModelState.IsValid)
            {
                _QuizService.CreateQuiz(_quiz);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Quiz/Edit/5
        public ActionResult Edit(int id)
        {
            Quiz quiz = _QuizService.GetQuizById(id);
            return View(quiz);
        }

        // POST: Quiz/Edit/5
        [HttpPost]
        public ActionResult Edit(Quiz quiz)
        {
            if(ModelState.IsValid)
            {
                _QuizService.UpdateQuiz(quiz);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Quiz/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_QuizService.GetQuizById(id));
        }

        // POST: Quiz/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                _QuizService.DeleteQuiz(id);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult ShowHighScoresForQuizID(int id)
        {
            IList<Score> scores;
            scores = _QuizService.GetScoresForQuizID(id);

            IList<HighScoresViewModel> viewModelList = new List<HighScoresViewModel>();

            foreach(Score score in scores)
            {
                HighScoresViewModel viewModel = new HighScoresViewModel()
                {
                    Score = score.Score1,
                    UserName = _UserService.GetUserByID(score.UserId).UserName.Split('@')[0],
                    QuizName = _QuizService.GetQuizById(score.quizid).Title,
                    Date = score.DateTime
                };
                viewModelList.Add(viewModel);
            }
            return View(viewModelList);
        }
    }
}

Globalwarmin/Views/Question/AskQuestion.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "AskQuestion";
    List<string> answers = new List<string>();
    answers.AddRange(Model.WrongAnswers.Split(','));
    answers.Add(Model.RightAnswer);

    Random random = new Random();
    int n = answers.Count;

    for (int i = answers.Count - 1; i > 1; i--)
    {
        int rnd = random.Next(i + 1);

        var value = answers[rnd];
        answers[rnd] = answers[i];
        answers[i] = value;
    }
}

<h2>@Model.QuestionText</h2>

<div>

    @foreach (string a in answers)
    {
        <a href="@Url.Action("AnswerQuestion", "Question" , new { thisquestionid = Model.QuestionId, clickedanswer = a })" class="btn btn-primary btn-lg">@a</a>
        <br />
    }
    <hr />
</div>

Globalwarmin/Views/Question/Create.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QuizId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuizId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightAnswer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RightAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WrongAnswers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WrongAnswers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WrongAnswers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightFeedback, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RightFeedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WrongFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WrongFeedback, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WrongFeedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Globalwarmin/Views/Question/Delete.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuizId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuizId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RightAnswer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RightAnswer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WrongAnswers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WrongAnswers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RightFeedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RightFeedback)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WrongFeedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WrongFeedback)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Globalwarmin/Views/Question/Details.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuizId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuizId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RightAnswer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RightAnswer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WrongAnswers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WrongAnswers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RightFeedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RightFeedback)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WrongFeedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WrongFeedback)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QuestionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Globalwarmin/Views/Question/Edit.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.QuestionId)

        <div class="form-group">
            @Html.LabelFor(model => model.QuizId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuizId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuizId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightAnswer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RightAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WrongAnswers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WrongAnswers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WrongAnswers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightFeedback, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RightFeedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuestionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WrongFeedback, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WrongFeedback, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WrongFeedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Globalwarmin/Views/Question/Endofquiz.cshtml
@model int

@{
    ViewBag.Title = "Endofquiz";
}

<h2>End of quiz</h2>
<h3>You scored @Model</h3>

<a href="@Url.Action("Index", "Quiz")"> Take another Quiz></a>

Globalwarmin/Views/Question/Index.cshtml
@model IEnumerable<Global.Data.Question>

@{
    ViewBag.Title = "Index";
}

<h2>Questions</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.QuizId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuestionText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RightAnswer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WrongAnswers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RightFeedback)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuestionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WrongFeedback)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.QuizId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuestionText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RightAnswer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WrongAnswers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RightFeedback)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuestionType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WrongFeedback)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.QuestionId }) |
            @Html.ActionLink("Details", "Details", new { id=item.QuestionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.QuestionId })
        </td>
    </tr>
}

</table>

Globalwarmin/Views/Question/success.cshtml
@model Global.Data.Question
@{
    ViewBag.Title = "success";
}

<h2>success</h2>
<h3>@Model.RightFeedback</h3>
<h4>You scored @Model.Score points</h4>
<a href="@Url.Action("NextQuestion", "Question")">Next Question</a>

Globalwarmin/Views/Question/wrong.cshtml
@model Global.Data.Question

@{
    ViewBag.Title = "wrong";
}

<h2>wrong</h2>
<h3>@Model.WrongFeedback</h3>
<a href="@Url.Action("NextQuestion", "Question")">Next Question</a>